# Generated by Django 3.2.12 on 2022-03-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rodajes', '0002_auto_20220318_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=350, null=True)),
                ('capitulos', models.ManyToManyField(to='Rodajes.Capitulo', verbose_name='Capitulo')),
            ],
        ),
    ]
