# Generated by Django 3.2.12 on 2022-03-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0002_auto_20220318_1401'),
        ('Rodajes', '0003_temporada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=350, null=True)),
                ('duracion', models.DurationField(help_text='Duracion en minutos de el capitulo', null=True)),
                ('puntuacion', models.FloatField(max_length=10.0, null=True)),
                ('director', models.ManyToManyField(related_name='pelicula_director', to='Personas.Persona', verbose_name='directores de la pelicula')),
                ('elenco', models.ManyToManyField(related_name='pelicula_elenco', to='Personas.Persona', verbose_name='Actores de la pelicula')),
                ('generos', models.ManyToManyField(to='Rodajes.Genero', verbose_name='Generos de la pelicula')),
                ('guionista', models.ManyToManyField(to='Personas.Persona', verbose_name='guionistas de la pelicula')),
            ],
        ),
    ]
