# Generated by Django 3.2.12 on 2022-03-18 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0002_auto_20220318_1401'),
        ('Rodajes', '0004_pelicula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=350, null=True)),
                ('creadores', models.ManyToManyField(to='Personas.Persona', verbose_name='Generos de la serie')),
                ('elenco', models.ManyToManyField(related_name='serie_elenco', to='Personas.Persona', verbose_name='Generos de la serie')),
                ('generos', models.ManyToManyField(to='Rodajes.Genero', verbose_name='Generos de la serie')),
                ('temporadas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rodajes.temporada', verbose_name='Temporadas de la Serie')),
            ],
        ),
    ]
