# Generated by Django 3.2.12 on 2022-03-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0002_auto_20220318_1401'),
        ('Rodajes', '0005_serie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='guionista',
            field=models.ManyToManyField(related_name='pelicula_guionista', to='Personas.Persona', verbose_name='guionistas de la pelicula'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='creadores',
            field=models.ManyToManyField(related_name='serie_creadores', to='Personas.Persona', verbose_name='Generos de la serie'),
        ),
    ]
