# Generated by Django 3.2.12 on 2022-03-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0002_auto_20220318_1401'),
        ('Rodajes', '0006_auto_20220318_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='director',
            field=models.ManyToManyField(blank=True, related_name='pelicula_director', to='Personas.Persona', verbose_name='Director/Directores'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='duracion',
            field=models.DurationField(help_text='Duracion en minutos de la pelicula', null=True),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='elenco',
            field=models.ManyToManyField(blank=True, related_name='pelicula_elenco', to='Personas.Persona', verbose_name='Elenco'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='generos',
            field=models.ManyToManyField(blank=True, to='Rodajes.Genero', verbose_name='Generos de la pelicula'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='guionista',
            field=models.ManyToManyField(blank=True, related_name='pelicula_guionista', to='Personas.Persona', verbose_name='guionistas de la pelicula'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='nombre',
            field=models.CharField(help_text='Nombre de la Pelicula', max_length=350, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='puntuacion',
            field=models.FloatField(help_text='Puntuacion del 0.00 al 10.00', max_length=10.0, null=True),
        ),
        migrations.AlterField(
            model_name='serie',
            name='creadores',
            field=models.ManyToManyField(blank=True, related_name='serie_creadores', to='Personas.Persona', verbose_name='Generos de la serie'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='elenco',
            field=models.ManyToManyField(blank=True, related_name='serie_elenco', to='Personas.Persona', verbose_name='Generos de la serie'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='generos',
            field=models.ManyToManyField(blank=True, to='Rodajes.Genero', verbose_name='Generos de la serie'),
        ),
        migrations.AlterField(
            model_name='temporada',
            name='capitulos',
            field=models.ManyToManyField(blank=True, to='Rodajes.Capitulo', verbose_name='Capitulo'),
        ),
        migrations.AlterField(
            model_name='temporada',
            name='nombre',
            field=models.IntegerField(max_length=100, verbose_name='Numero de temporada'),
        ),
    ]
