# Generated by Django 3.2.12 on 2022-03-20 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rodajes', '0007_auto_20220320_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporada',
            name='nombre',
            field=models.IntegerField(verbose_name='Numero de temporada'),
        ),
    ]
