# Generated by Django 3.2.12 on 2022-03-27 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rodajes', '0008_alter_temporada_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='temporadas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Rodajes.temporada', verbose_name='Temporadas de la Serie'),
        ),
    ]
