# Generated by Django 3.2.12 on 2022-03-27 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rodajes', '0009_alter_serie_temporadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='temporadas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Rodajes.temporada', verbose_name='Temporadas de la Serie'),
        ),
    ]
