# Generated by Django 3.2.12 on 2022-03-27 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rodajes', '0010_alter_serie_temporadas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporada',
            name='capitulos',
        ),
        migrations.AddField(
            model_name='temporada',
            name='capitulos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='capitulos', to='Rodajes.capitulo', verbose_name='Capitulos'),
        ),
    ]
