# Generated by Django 3.2.12 on 2022-03-28 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rodajes', '0012_remove_serie_temporadas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temporada',
            old_name='nombre',
            new_name='numero',
        ),
        migrations.RemoveField(
            model_name='temporada',
            name='capitulos',
        ),
        migrations.AddField(
            model_name='capitulo',
            name='temporada',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='temporada', to='Rodajes.temporada', verbose_name='Temporada'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temporada',
            name='serie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='capitulos', to='Rodajes.serie', verbose_name='Capitulos'),
            preserve_default=False,
        ),
    ]
