# Generated by Django 3.2.12 on 2022-03-28 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rodajes', '0014_auto_20220328_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitulo',
            name='puntuacion',
            field=models.FloatField(help_text='Puntuacion del 0.00 al 10.00', max_length=10.0, null=True),
        ),
    ]
