# Generated by Django 3.2.12 on 2022-03-28 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rodajes', '0015_alter_capitulo_puntuacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='slug',
            field=models.SlugField(max_length=350, null=True),
        ),
    ]
