# Generated by Django 3.2.12 on 2022-03-28 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rodajes', '0016_serie_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serie',
            name='slug',
        ),
    ]
