# Generated by Django 3.2.12 on 2022-03-28 02:20

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rodajes', '0019_remove_serie_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default='hola', editable=False, max_length=350, populate_from='nombre', unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
