# Generated by Django 3.2.12 on 2022-03-28 02:23

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rodajes', '0020_serie_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, help_text='Slug autogenerado', max_length=350, populate_from='nombre', unique=True, verbose_name='Slug'),
        ),
    ]
