# Generated by Django 3.2.12 on 2022-03-28 02:27

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rodajes', '0021_alter_serie_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default='the-project-adam', editable=False, help_text='Slug autogenerado', max_length=350, populate_from='nombre', unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
