# Generated by Django 3.2.12 on 2022-04-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0006_persona_usuario'),
        ('Rodajes', '0022_pelicula_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='creadores',
            field=models.ManyToManyField(blank=True, related_name='serie_creadores', to='Personas.Persona', verbose_name='Creadores de la serie'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='elenco',
            field=models.ManyToManyField(blank=True, related_name='serie_elenco', to='Personas.Persona', verbose_name='Elenco Actoral de la serie'),
        ),
    ]
