# Generated by Django 3.2.12 on 2022-04-08 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rodajes', '0023_auto_20220402_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitulo',
            name='temporada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capitulos', to='Rodajes.temporada', verbose_name='Temporada'),
        ),
        migrations.AlterField(
            model_name='temporada',
            name='serie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporadas', to='Rodajes.serie', verbose_name='Serie'),
        ),
    ]
