# Generated by Django 3.2.12 on 2022-04-24 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rodajes', '0024_auto_20220408_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='año',
            field=models.IntegerField(help_text='Año del estreno', null=True, verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='temporada',
            name='numero',
            field=models.IntegerField(verbose_name='Numero de temporada'),
        ),
    ]
