# Generated by Django 3.2.12 on 2022-04-25 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rodajes', '0025_auto_20220424_0157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='director',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='elenco',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='guionista',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='creadores',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='elenco',
        ),
    ]
