# Generated by Django 3.2.12 on 2022-04-25 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0013_auto_20220408_1151'),
        ('Rodajes', '0026_auto_20220425_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elenco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actores', models.ManyToManyField(blank=True, related_name='elenco_actores', to='Personas.Persona', verbose_name='Elenco Actoral de la Pelicula/Serie')),
                ('directores', models.ManyToManyField(blank=True, related_name='elenco_director', to='Personas.Persona', verbose_name='Director/Directores')),
                ('guionistas', models.ManyToManyField(blank=True, related_name='elenco_guionista', to='Personas.Persona', verbose_name='Guionistas/Creadores de la Serie/Pelicula')),
            ],
        ),
        migrations.AddField(
            model_name='pelicula',
            name='elenco',
            field=models.OneToOneField(blank=True, help_text='Elenco de la pelicula', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pelicula_elenco', to='Rodajes.elenco', verbose_name='Elenco'),
        ),
        migrations.AddField(
            model_name='serie',
            name='elenco',
            field=models.OneToOneField(blank=True, help_text='Elenco de la serie', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='serie_elenco', to='Rodajes.elenco', verbose_name='Elenco'),
        ),
    ]
