# Generated by Django 3.2.12 on 2022-04-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0017_persona_tipo'),
        ('Rodajes', '0029_auto_20220430_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='elenco',
            name='personas',
            field=models.ManyToManyField(blank=True, related_name='personas_elenco', to='Personas.Persona', verbose_name='Personas'),
        ),
    ]
