# Generated by Django 3.2.12 on 2022-04-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0017_persona_tipo'),
        ('Rodajes', '0030_elenco_personas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elenco',
            old_name='personas',
            new_name='actores',
        ),
        migrations.AddField(
            model_name='elenco',
            name='directores',
            field=models.ManyToManyField(blank=True, related_name='directores_elenco', to='Personas.Persona', verbose_name='Directores'),
        ),
        migrations.AddField(
            model_name='elenco',
            name='guionistas',
            field=models.ManyToManyField(blank=True, related_name='guionistas_elenco', to='Personas.Persona', verbose_name='Guionistas'),
        ),
    ]
