# Generated by Django 3.2.12 on 2022-04-30 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rodajes', '0031_auto_20220430_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elenco',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='elenco',
            name='object_id',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='elenco',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Rodajes.elenco'),
        ),
        migrations.AddField(
            model_name='serie',
            name='elenco',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Rodajes.elenco'),
        ),
    ]
