# Generated by Django 3.2.12 on 2022-05-01 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rodajes', '0032_auto_20220430_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='elenco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Rodajes.elenco'),
        ),
    ]
