# Generated by Django 3.2.12 on 2022-05-01 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rodajes', '0033_alter_pelicula_elenco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='elenco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elenco_pelicula', to='Rodajes.elenco'),
        ),
    ]
