# Generated by Django 3.2.12 on 2022-05-02 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rodajes', '0034_alter_pelicula_elenco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='año',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='anio',
            field=models.PositiveSmallIntegerField(help_text='Año del estreno', null=True, verbose_name='Año'),
        ),
    ]
