# Generated by Django 3.2.12 on 2022-03-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='debut',
            field=models.DateField(help_text='Fecha en que debuto', null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='fecha_nacimiento',
            field=models.DateField(help_text='Fecha en que nacio', null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='pais',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
