# Generated by Django 3.2.12 on 2022-03-21 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0002_auto_20220318_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='sexo',
            field=models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], default='H', max_length=1),
        ),
    ]
