# Generated by Django 3.2.12 on 2022-03-28 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0004_persona_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='usuario',
        ),
    ]
