# Generated by Django 3.2.12 on 2022-04-02 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0007_auto_20220402_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, help_text='Nombre del pais', max_length=90, null=True, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, help_text='Nombre de la persona', max_length=90, null=True, verbose_name='Nombre')),
            ],
        ),
        migrations.AddField(
            model_name='persona',
            name='tipo',
            field=models.ForeignKey(blank=True, help_text='Tipo: Guinista, Actor, Director, Creador...', null=True, on_delete=django.db.models.deletion.CASCADE, to='Personas.tipo', verbose_name='Tipo de persona'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='pais',
            field=models.ForeignKey(blank=True, help_text='Pais de nacimiento', null=True, on_delete=django.db.models.deletion.CASCADE, to='Personas.pais', verbose_name='Pais'),
        ),
    ]
