# Generated by Django 3.2.12 on 2022-04-02 13:42

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0008_auto_20220402_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, help_text='Slug autogenerado', max_length=350, populate_from='nombreapellido', unique=True, verbose_name='Slug'),
        ),
    ]
