# Generated by Django 3.2.12 on 2022-04-02 14:05

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0009_alter_persona_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pais',
            options={'verbose_name': 'Pais', 'verbose_name_plural': 'Paises'},
        ),
        migrations.RemoveField(
            model_name='persona',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='persona',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, help_text='Slug autogenerado', max_length=350, populate_from='apellido', unique=True, verbose_name='Slug'),
        ),
    ]
