# Generated by Django 3.2.12 on 2022-04-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0010_auto_20220402_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='tipo',
            field=models.ManyToManyField(blank=True, help_text='Tipo: Guinista, Actor, Director, Creador...', null=True, to='Personas.Tipo', verbose_name='Tipo de persona'),
        ),
    ]
