# Generated by Django 3.2.12 on 2022-04-08 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0012_alter_persona_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='slug',
            new_name='slugname',
        ),
        migrations.AlterField(
            model_name='persona',
            name='pais',
            field=models.ForeignKey(blank=True, help_text='Pais de nacimiento', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persona_pais', to='Personas.pais', verbose_name='Pais'),
        ),
    ]
