# Generated by Django 3.2.12 on 2022-04-25 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0013_auto_20220408_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='tipo',
        ),
    ]
