# Generated by Django 3.2.12 on 2022-04-25 16:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0014_remove_persona_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='tipo',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('A', 'Actor'), ('D', 'Director'), ('G', 'Guionista')], max_length=1, null=True), blank=True, null=True, size=None),
        ),
    ]
